version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "3001:3001"
    command: npm run dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"  # 80 no container (nginx), 3000 no host
